### ISSUE TITLE
Handle HDD size when creating a new engine

### ISSUE THREAD

**Issue by Kiniamaro** [turbulent/substance#32]
Currently, it's possible to define the number of cpus and the amount of ram the engine will have, however, HDD size is not possible to be set.

this can be problematic if you need a box bigger then the default size of 80GB, which arguably if you have a box this big, you might have other underlying problems... but none the less this is something that should be configurable.

**Comment by Kiniamaro** [comment]
After investigation, HDD size is defined on a per image basis, which makes a lot of sense considering this lets you possibly have multiple partitions on your engine.

 Also, resizing a `.vmdk` file requires you to first convert it to a `.vdi` then resize this `.vdi`, and convert it back to a `.vmdk`, which is definitely doable but when this operation is not supported as a single command by `$ vboxmanage` it begs the question that **bbeausej** brought up in #15, "is this really part of the scope of substance?". Which after looking into this I'm leaning more towards a "no it's not."

**Comment by bbeausej** [comment]
I forget why we chose to use vmdk in the beginning. I think it's because it had better handling of thin provisioning over vdi. We could reconsider adding more HDD/underlying image support for this in the future if we ever get rid of the vmdk dependency and can manip the engine's disk image with vboxmanage.
